"""
Catalog metadata, prompts, and resources for Sandbox MCP.

This module keeps presentation-oriented metadata in one place so the runtime
surface exposed to MCP clients stays aligned with repository documentation.
"""

from __future__ import annotations

import importlib.metadata
from typing import Any


def _package_version() -> str:
    """Return the installed package version or a development fallback."""
    for distribution_name in ("sandbox-mcp", "sandbox"):
        try:
            return importlib.metadata.version(distribution_name)
        except importlib.metadata.PackageNotFoundError:
            continue
    return "0.1.0-dev"


SERVER_ID = "sandbox-mcp"
SERVER_PACKAGE_NAME = "sandbox-mcp"
SERVER_REGISTRY_NAME = "io.github.scooter-lacroix/sandbox-mcp"
SERVER_NAME = "Sandbox MCP"
SERVER_SUMMARY = (
    "General-purpose Python execution sandbox for running code, capturing "
    "artifacts, rendering Manim scenes, and exporting lightweight demos over MCP."
)
SERVER_DESCRIPTION = (
    "Sandbox MCP gives language models a guarded Python workspace with persistent "
    "execution state, shell access with security filtering, artifact management, "
    "Manim rendering, package installation, and small web app workflows. It is "
    "designed to stay broadly useful for experimentation, teaching, demos, "
    "analysis, and prototyping rather than being tied to one marketplace or "
    "one domain."
)
SERVER_INSTRUCTIONS = (
    "Sandbox MCP is a general-purpose Python execution server. Use it for short "
    "Python tasks, shell commands that stay within the guarded environment, "
    "artifact-heavy workflows such as plots/images/videos, Manim animation "
    "generation, package inspection, and lightweight Flask or Streamlit demos. "
    "Prefer the execution and artifact tools for runnable examples, use the "
    "catalog resources to discover capabilities, and use the interactive prompts "
    "when the user wants a ready-to-generate Manim scene or sandbox example. "
    "This is a guarded execution environment, not a hardened multi-tenant "
    "container or VM."
)

TOOL_METADATA: dict[str, dict[str, Any]] = {
    "execute": {
        "description": "Run Python code in the sandbox with persistent state, artifact capture, and optional web app launch.",
        "tags": {"python", "execution", "core"},
    },
    "list_artifacts": {
        "description": "List files generated by sandbox runs, including plots, images, animations, and exports.",
        "tags": {"artifacts", "files", "inspection"},
    },
    "clear_cache": {
        "description": "Clear cached compilations and related execution state to force a fresh run path.",
        "tags": {"execution", "cache", "maintenance"},
    },
    "cleanup_artifacts": {
        "description": "Remove current artifacts and stop any tracked web app processes created by the sandbox.",
        "tags": {"artifacts", "cleanup", "maintenance"},
    },
    "start_repl": {
        "description": "Start the basic interactive Python REPL workflow exposed by the sandbox.",
        "tags": {"python", "repl", "interactive"},
    },
    "start_web_app": {
        "description": "Launch a small Flask or Streamlit app from code and return its local access URL.",
        "tags": {"web", "flask", "streamlit"},
    },
    "cleanup_temp_artifacts": {
        "description": "Delete old temporary sandbox artifact directories older than the requested age threshold.",
        "tags": {"artifacts", "cleanup", "maintenance"},
    },
    "shell_execute": {
        "description": "Run a shell command inside the guarded environment with security checks and a timeout.",
        "tags": {"shell", "execution", "security"},
    },
    "create_manim_animation": {
        "description": "Render a Manim Community animation from provided scene code and return output metadata.",
        "tags": {"manim", "animation", "video"},
    },
    "list_manim_animations": {
        "description": "List Manim renders created by the sandbox and their saved artifact locations.",
        "tags": {"manim", "animation", "artifacts"},
    },
    "cleanup_manim_animation": {
        "description": "Delete one saved Manim render by its animation identifier.",
        "tags": {"manim", "cleanup", "artifacts"},
    },
    "get_manim_examples": {
        "description": "Return small Manim example scenes that can be adapted into new animations immediately.",
        "tags": {"manim", "examples", "templates"},
    },
    "get_execution_info": {
        "description": "Inspect the current sandbox environment, including paths, virtualenv status, and tracked globals.",
        "tags": {"environment", "inspection", "diagnostics"},
    },
    "get_artifact_report": {
        "description": "Summarize current artifacts with category counts and persistent execution context details.",
        "tags": {"artifacts", "reporting", "inspection"},
    },
    "categorize_artifacts": {
        "description": "Group current artifacts into higher-level categories such as plots, images, data, and videos.",
        "tags": {"artifacts", "classification", "organization"},
    },
    "cleanup_artifacts_by_type": {
        "description": "Delete artifacts from one category without clearing the rest of the sandbox outputs.",
        "tags": {"artifacts", "cleanup", "organization"},
    },
    "start_enhanced_repl": {
        "description": "Start the enhanced REPL workflow with helper commands for artifacts, packages, and Manim.",
        "tags": {"python", "repl", "interactive"},
    },
    "execute_with_artifacts": {
        "description": "Run Python code while explicitly tracking resulting artifacts and execution metadata.",
        "tags": {"python", "execution", "artifacts"},
    },
    "backup_current_artifacts": {
        "description": "Create a named backup snapshot of the current artifact set for rollback or comparison.",
        "tags": {"artifacts", "backup", "versioning"},
    },
    "list_artifact_backups": {
        "description": "List saved artifact backups with sizes, timestamps, and file counts.",
        "tags": {"artifacts", "backup", "inspection"},
    },
    "rollback_to_backup": {
        "description": "Restore artifacts from a saved backup snapshot into the current sandbox workspace.",
        "tags": {"artifacts", "backup", "rollback"},
    },
    "get_backup_details": {
        "description": "Inspect one artifact backup in detail, including categories and contained files.",
        "tags": {"artifacts", "backup", "inspection"},
    },
    "cleanup_old_backups": {
        "description": "Prune older artifact backups and keep only the requested number of recent snapshots.",
        "tags": {"artifacts", "backup", "cleanup"},
    },
    "export_web_app": {
        "description": "Package a Flask or Streamlit app into an exportable project with deployment assets.",
        "tags": {"web", "export", "deployment"},
    },
    "list_web_app_exports": {
        "description": "List previously exported web app bundles and their generated deployment files.",
        "tags": {"web", "export", "inspection"},
    },
    "get_export_details": {
        "description": "Inspect one exported web app bundle, including files, metadata, and status.",
        "tags": {"web", "export", "inspection"},
    },
    "build_docker_image": {
        "description": "Build a Docker image from an exported web app bundle for local or hosted deployment.",
        "tags": {"web", "docker", "deployment"},
    },
    "cleanup_web_app_export": {
        "description": "Delete one exported web app bundle and its generated deployment assets.",
        "tags": {"web", "export", "cleanup"},
    },
    "install_package": {
        "description": "Install a Python package into the sandbox environment, optionally pinning a version.",
        "tags": {"packages", "python", "environment"},
    },
    "list_installed_packages": {
        "description": "List the Python packages currently available to sandbox executions.",
        "tags": {"packages", "python", "inspection"},
    },
    "get_sandbox_limitations": {
        "description": "Explain sandbox constraints, available subsystems, and recommended workarounds.",
        "tags": {"help", "limits", "diagnostics"},
    },
    "get_comprehensive_help": {
        "description": "Return a structured usage guide covering execution, artifacts, packages, web apps, and Manim.",
        "tags": {"help", "examples", "guide"},
    },
}

SKILLS: list[dict[str, Any]] = [
    {
        "id": "manim_storyboard_skill",
        "title": "Manim Storyboard Skill",
        "kind": "skill",
        "description": "Turns a concept into a storyboard, a renderable Manim scene, and a suggested sandbox workflow.",
        "activation_prompt": "manim_storyboard_skill",
        "recommended_tools": [
            "get_manim_examples",
            "create_manim_animation",
            "list_manim_animations",
            "list_artifacts",
        ],
        "outputs": [
            "creative brief",
            "scene-by-scene plan",
            "ready-to-render Manim code",
            "optional narration",
        ],
    }
]

INTERACTIVE_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "manim_scene_template",
        "title": "Manim Scene Template",
        "type": "prompt",
        "description": "Generate a single self-contained Manim scene from a concept, duration target, and quality preset.",
        "prompt": "manim_scene_template",
        "best_for": ["math explainers", "motion graphics", "classroom visuals"],
    },
    {
        "id": "sandbox_example_template",
        "title": "Sandbox Example Template",
        "type": "prompt",
        "description": "Generate a compact sandbox demo that creates an artifact such as a plot, image, table, or data file.",
        "prompt": "sandbox_example_template",
        "best_for": ["sample outputs", "tests of artifact capture", "quick tutorials"],
    },
    {
        "id": "sandbox_web_app_template",
        "title": "Sandbox Web App Template",
        "type": "prompt",
        "description": "Generate a small Flask or Streamlit demo that is ready for launch or export from the sandbox.",
        "prompt": "sandbox_web_app_template",
        "best_for": ["interactive demos", "rapid prototypes", "deployment walkthroughs"],
    },
]

PROMPT_METADATA: list[dict[str, Any]] = [
    {
        "name": "manim_storyboard_skill",
        "title": "Manim Storyboard Skill",
        "description": "Skill prompt that turns an idea into a storyboard, renderable Manim code, and a tool-by-tool execution plan.",
        "tags": ["skill", "manim", "template"],
    },
    {
        "name": "manim_scene_template",
        "title": "Manim Scene Template",
        "description": "Interactive prompt for generating a focused Manim scene tailored to the sandbox renderer.",
        "tags": ["prompt", "manim", "template"],
    },
    {
        "name": "sandbox_example_template",
        "title": "Sandbox Example Template",
        "description": "Interactive prompt for generating runnable sandbox examples that create useful artifacts.",
        "tags": ["prompt", "examples", "template"],
    },
    {
        "name": "sandbox_web_app_template",
        "title": "Sandbox Web App Template",
        "description": "Interactive prompt for generating a minimal Flask or Streamlit demo that can be launched or exported.",
        "tags": ["prompt", "web", "template"],
    },
]

RESOURCE_METADATA: list[dict[str, Any]] = [
    {
        "uri": "sandbox://server/overview",
        "name": "sandbox_server_overview",
        "description": "Structured summary of the server, its capabilities, and recommended usage patterns.",
    },
    {
        "uri": "sandbox://catalog/interfaces",
        "name": "sandbox_llm_interfaces",
        "description": "Machine-readable overview of the tools, prompts, resources, skills, and interactive templates exposed to the LLM.",
    },
    {
        "uri": "sandbox://catalog/skills",
        "name": "sandbox_skill_catalog",
        "description": "Machine-readable list of higher-level skills available from the sandbox server.",
    },
    {
        "uri": "sandbox://catalog/templates",
        "name": "sandbox_template_catalog",
        "description": "Machine-readable list of user-activated interactive templates exposed as MCP prompts.",
    },
    {
        "uri": "sandbox://catalog/skill/{skill_name}",
        "name": "sandbox_skill_detail",
        "description": "Details for one skill entry from the skill catalog.",
    },
    {
        "uri": "sandbox://catalog/template/{template_name}",
        "name": "sandbox_template_detail",
        "description": "Details for one interactive template entry from the template catalog.",
    },
]


def build_server_overview() -> dict[str, Any]:
    """Return a structured overview suitable for MCP resources and docs."""
    return {
        "id": SERVER_ID,
        "package_name": SERVER_PACKAGE_NAME,
        "registry_name": SERVER_REGISTRY_NAME,
        "name": SERVER_NAME,
        "version": _package_version(),
        "summary": SERVER_SUMMARY,
        "description": SERVER_DESCRIPTION,
        "transports": ["stdio", "streamable-http"],
        "best_for": [
            "running short Python examples",
            "creating plots, images, tables, and file artifacts",
            "rendering Manim animations",
            "launching or exporting small Flask and Streamlit demos",
            "teaching, prototyping, and reproducible walkthroughs",
        ],
        "not_for": [
            "hard multi-tenant isolation",
            "long-running background workloads",
            "untrusted production workloads without an outer container or VM",
        ],
        "capabilities": [
            "persistent Python execution context",
            "artifact capture and categorization",
            "guarded shell execution",
            "package management inside the sandbox environment",
            "Manim rendering and example retrieval",
            "web app launch and export workflows",
            "catalog resources, skills, and interactive prompt templates",
        ],
        "interface_counts": {
            "tools": len(TOOL_METADATA),
            "prompts": len(PROMPT_METADATA),
            "resources": len(RESOURCE_METADATA),
            "skills": len(SKILLS),
            "interactive_templates": len(INTERACTIVE_TEMPLATES),
        },
    }


def build_interface_catalog() -> dict[str, Any]:
    """Return the combined LLM interface catalog."""
    return {
        "server": build_server_overview(),
        "tools": [
            {
                "name": name,
                "description": metadata["description"],
                "tags": sorted(metadata["tags"]),
            }
            for name, metadata in TOOL_METADATA.items()
        ],
        "prompts": PROMPT_METADATA,
        "resources": RESOURCE_METADATA,
        "skills": SKILLS,
        "interactive_templates": INTERACTIVE_TEMPLATES,
    }


def _find_entry(entries: list[dict[str, Any]], key: str, value: str) -> dict[str, Any]:
    """Return one matching catalog entry or a structured error payload."""
    for entry in entries:
        if entry.get(key) == value:
            return entry

    return {
        "status": "error",
        "message": f"No catalog entry found for {key}={value!r}.",
        "available": [entry.get(key) for entry in entries],
    }


def register_catalog_primitives(mcp: Any) -> None:
    """Register descriptive resources and user-activated prompts."""

    @mcp.resource(
        "sandbox://server/overview",
        name="sandbox_server_overview",
        description="Structured summary of the server, its capabilities, and recommended usage patterns.",
        mime_type="application/json",
        tags={"catalog", "about"},
    )
    def sandbox_server_overview():
        return build_server_overview()

    @mcp.resource(
        "sandbox://catalog/interfaces",
        name="sandbox_llm_interfaces",
        description="Machine-readable overview of tools, prompts, resources, skills, and templates exposed by Sandbox MCP.",
        mime_type="application/json",
        tags={"catalog", "interfaces"},
    )
    def sandbox_llm_interfaces():
        return build_interface_catalog()

    @mcp.resource(
        "sandbox://catalog/skills",
        name="sandbox_skill_catalog",
        description="Machine-readable list of higher-level skills available from the sandbox server.",
        mime_type="application/json",
        tags={"catalog", "skill"},
    )
    def sandbox_skill_catalog():
        return {"skills": SKILLS}

    @mcp.resource(
        "sandbox://catalog/templates",
        name="sandbox_template_catalog",
        description="Machine-readable list of user-activated interactive templates exposed as MCP prompts.",
        mime_type="application/json",
        tags={"catalog", "template"},
    )
    def sandbox_template_catalog():
        return {"interactive_templates": INTERACTIVE_TEMPLATES}

    @mcp.resource(
        "sandbox://catalog/skill/{skill_name}",
        name="sandbox_skill_detail",
        description="Details for one skill entry from the skill catalog.",
        mime_type="application/json",
        tags={"catalog", "skill"},
    )
    def sandbox_skill_detail(skill_name: str):
        return _find_entry(SKILLS, "id", skill_name)

    @mcp.resource(
        "sandbox://catalog/template/{template_name}",
        name="sandbox_template_detail",
        description="Details for one interactive template entry from the template catalog.",
        mime_type="application/json",
        tags={"catalog", "template"},
    )
    def sandbox_template_detail(template_name: str):
        return _find_entry(INTERACTIVE_TEMPLATES, "id", template_name)

    @mcp.prompt(
        name="manim_storyboard_skill",
        description="Skill prompt that turns an idea into a storyboard, renderable Manim code, and a tool-by-tool execution plan.",
        tags={"skill", "manim", "template"},
    )
    def manim_storyboard_skill(
        concept: str,
        audience: str = "general",
        visual_style: str = "clean geometric motion design",
        include_narration: bool = False,
    ) -> str:
        narration_line = (
            "Include a short narration script aligned with the scene beats."
            if include_narration
            else "Do not include narration."
        )
        return f"""
Create a Sandbox MCP Manim deliverable for the following concept.

Concept: {concept}
Audience: {audience}
Visual style: {visual_style}

Respond with:
- A 2-4 sentence creative brief.
- A scene-by-scene storyboard with approximate timing.
- Complete Manim Community code with exactly one renderable `Scene` subclass.
- A short note explaining which Sandbox MCP tools to call next: `get_manim_examples`, `create_manim_animation`, `list_manim_animations`, and `list_artifacts`.
- A short adaptation note describing how to simplify or extend the animation.

Constraints:
- Keep the code self-contained and ready for `create_manim_animation`.
- Use a 16:9-friendly composition and readable text sizing.
- Avoid external assets unless they are strictly necessary.
- {narration_line}
""".strip()

    @mcp.prompt(
        name="manim_scene_template",
        description="Interactive prompt for generating a focused Manim scene tailored to the sandbox renderer.",
        tags={"prompt", "manim", "template"},
    )
    def manim_scene_template(
        concept: str,
        duration_seconds: int = 6,
        quality: str = "medium_quality",
    ) -> str:
        return f"""
Write complete Manim Community scene code for the Sandbox MCP environment.

Concept: {concept}
Target duration: about {duration_seconds} seconds
Render quality preset: {quality}

Return:
- One short sentence describing the visual idea.
- Complete self-contained Python code using `from manim import *`.
- A final line telling the model it can render the result with `create_manim_animation`.

Keep the animation crisp, readable, and easy to adapt.
""".strip()

    @mcp.prompt(
        name="sandbox_example_template",
        description="Interactive prompt for generating runnable sandbox examples that create useful artifacts.",
        tags={"prompt", "examples", "template"},
    )
    def sandbox_example_template(
        goal: str,
        artifact_type: str = "plot",
        libraries: str = "numpy, matplotlib",
    ) -> str:
        return f"""
Generate a compact Python example for Sandbox MCP.

Goal: {goal}
Desired artifact type: {artifact_type}
Preferred libraries: {libraries}

Return:
- A short explanation of the example.
- Runnable Python code intended for the `execute` tool.
- A note describing which artifact should appear in `list_artifacts`.

Prefer examples that finish quickly and visibly demonstrate the sandbox.
""".strip()

    @mcp.prompt(
        name="sandbox_web_app_template",
        description="Interactive prompt for generating a minimal Flask or Streamlit demo that can be launched or exported.",
        tags={"prompt", "web", "template"},
    )
    def sandbox_web_app_template(
        idea: str,
        framework: str = "streamlit",
        include_export_notes: bool = True,
    ) -> str:
        export_line = (
            "Include a short note about `start_web_app`, `export_web_app`, and `build_docker_image`."
            if include_export_notes
            else "Do not include export guidance."
        )
        return f"""
Generate a small {framework} demo for Sandbox MCP.

App idea: {idea}

Return:
- A one-paragraph summary of the app.
- Complete runnable code suitable for `start_web_app`.
- A short explanation of what the user should expect when launching it.
- {export_line}

Keep the example small, self-contained, and easy to package.
""".strip()


__all__ = [
    "INTERACTIVE_TEMPLATES",
    "PROMPT_METADATA",
    "RESOURCE_METADATA",
    "SERVER_DESCRIPTION",
    "SERVER_ID",
    "SERVER_INSTRUCTIONS",
    "SERVER_NAME",
    "SERVER_PACKAGE_NAME",
    "SERVER_REGISTRY_NAME",
    "SERVER_SUMMARY",
    "SKILLS",
    "TOOL_METADATA",
    "build_interface_catalog",
    "build_server_overview",
    "register_catalog_primitives",
]
